total_clusters: 10000
lattice_constant: !Quantity
  unit: nanometer
  value: [800.0, 800.0, 800.0]
box_size: !Quantity
  unit: nanometer
  value: [9000.0, 9000.0, 90000.0]
random_rotation: false
cluster_order: ["A", "A", "B"]
masses:
  A: !Quantity
    unit: dalton
    value: 0.7406327610409243
  B: !Quantity
    unit: dalton
    value: 1.0
  C: !Quantity
    unit: dalton
    value: 1.0
radii:
  A: !Quantity
    unit: nanometer
    value: 59.39696961966999204974
  B: !Quantity
    unit: nanometer
    value: 105.0
  C: !Quantity
    unit: nanometer
    value: 52.5
surface_potentials:
  A: !Quantity
    unit: millivolt
    value: -54.0
  B: !Quantity
    unit: millivolt
    value: 44.0
  C: !Quantity
    unit: millivolt
    value: -44.0
cluster_specifications:
  A:
    identity:
      - "A"
    coordinates: !Quantity
      unit: nanometer
      value:
      - [0.0, 0.0, 0.0]
  B:
    identity:
      - "B"
      - "B"
      - "B"
      - "B"
      - "C"
    coordinates: !Quantity
      unit: nanometer
      value:
      - [105.0, 105.0, 105.0]
      - [-105.0, -105.0, 105.0]
      - [105.0, -105.0, -105.0]
      - [-105.0, 105.0, -105.0]
      - [0.0, 0.0, 0.0]