cif: null
cluster_specifications: 
 - "cluster.lmp"
cluster_relative_weights:
  - 1.0
lattice_repeats: 2
cluster_padding_factor: 3.0
padding_factor: 1.5
lattice_scale_factor: null
lattice_scale_start: null
lattice_vector_scaling_matrix: null
radii_padding_factor: null
masses:
  "1": !Quantity
    unit: dalton
    value: 1.0
  "2": !Quantity
    unit: dalton
    value: 1.0
  "3": !Quantity
    unit: dalton
    value: 1.0
radii:
  "1": !Quantity
    unit: nanometer
    value: 1.0
  "2": !Quantity
    unit: nanometer
    value: 1.0
  "3": !Quantity
    unit: nanometer
    value: 1.0
surface_potentials:
  "1": !Quantity
    unit: millivolt
    value: 50.0
  "2": !Quantity
    unit: millivolt
    value: -30.0
  "3": !Quantity
    unit: millivolt
    value: 40.0
brush_length: null
random_rotation: true
initial_modifiers: null
initial_modifiers_parameters: null
final_modifiers: null
final_modifiers_parameters: null
