cif: structure.cif
cluster_specifications: 
 - "cluster.lmp"
cluster_relative_weights:
  - 1.0
lattice_repeats: 2
cluster_padding_factor: null #3.0
padding_factor: null #1.5
lattice_spacing: 15.0
lattice_scale_factor: 0.5
lattice_scale_start: 50.0
optimize_lattice: false
lattice_scale_rate: 0.005
masses:
  "1": !Quantity
    unit: dalton
    value: 1.0
  "2": !Quantity
    unit: dalton
    value: 1.0
  "3": !Quantity
    unit: dalton
    value: 1.0
radii:
  "1": !Quantity
    unit: nanometer
    value: 1.0
  "2": !Quantity
    unit: nanometer
    value: 1.0
  "3": !Quantity
    unit: nanometer
    value: 1.0
surface_potentials:
  "1": !Quantity
    unit: millivolt
    value: 50.0
  "2": !Quantity
    unit: millivolt
    value: -30.0
  "3": !Quantity
    unit: millivolt
    value: 40.0
brush_length: !Quantity
    unit: nanometer
    value: 10.0
random_rotation: null #true
initial_modifiers: null
initial_modifiers_parameters: null
final_modifiers: null
final_modifiers_parameters: null
