from abc import ABC, abstractmethod
from gsd.hoomd import Frame
from openmm import unit


class ConfigurationGenerator(ABC):
    """
    Abstract base class for a generator of an initial configuration in a gsd.hoomd.Frame instance for a colloid
    simulation.

    This generator receives the masses, radii, and surface potentials dictionaries to be able to use them during
    configuration generation if necessary.

    :param masses:
        The masses dictionary with the particle types as keys and the masses as values.
    :type masses: dict[str, unit.Quantity]
    :param radii:
        The radii dictionary with the particle types as keys and the radii as values.
    :type radii: dict[str, unit.Quantity]
    :param surface_potentials:
        The surface potentials dictionary with the particle types as keys and the surface potentials as values.
    :type surface_potentials: dict[str, unit.Quantity]
    """

    # noinspection PyUnusedLocal
    def __init__(self, masses: dict[str, unit.Quantity], radii: dict[str, unit.Quantity],
                 surface_potentials: dict[str, unit.Quantity]) -> None:
        """Constructor of the ConfigurationGenerator class."""
        pass

    @abstractmethod
    def types(self) -> set[str]:
        """
        Return the set of particle types that will be generated by this configuration generator.

        :return:
            The set of particle types that will be generated by this configuration generator.
        :rtype: set[str]
        """
        raise NotImplementedError

    @abstractmethod
    def generate_configuration(self) -> Frame:
        """
        Generate the initial positions of the colloids in a gsd.hoomd.Frame instance together with constraints.

        The generated frame should contain the following attributes:
        - frame.particles.N
        - frame.particles.position
        - frame.particles.types
        - frame.particles.typeid
        - frame.configuration.box
        - frame.constraints.N (optionally if constraints are present)
        - frame.constraints.value (optionally if constraints are present)
        - frame.constraints.group (optionally if constraints are present)

        The generated frame should not populate the following attributes:
        - frame.particles.type_shapes
        - frame.particles.diameter
        - frame.particles.charge
        - frame.particles.mass attributes

        :return:
            The initial configuration of the colloids.
        :rtype: gsd.hoomd.Frame
        """
        raise NotImplementedError
