final_modifiers:
- "SeedModifier"
- "SeedModifier"
final_modifiers_parameters:
  - seed_filename: CsCl.gsd
    overlap_distance: !Quantity
      unit: nanometer
      value: 230.0
    cluster_cutoff_distance: !Quantity
      unit: nanometer
      value: 230.0
    #seed_fractional_position: [0.25, 0.25, 0.25]
    seed_frame_index: -1
  - seed_filename: Th3P4.gsd
    overlap_distance: !Quantity
      unit: nanometer
      value: 230.0
    cluster_cutoff_distance: !Quantity
      unit: nanometer
      value: 230.0
    #seed_fractional_position: [0.75, 0.75, 0.75]
    seed_frame_index: -1
configuration_generator: ClusterGenerator
configuration_generator_parameters:
  cluster_specifications:
    - "cluster.lmp"
  cluster_relative_weights:
    - 1.0
  lattice_repeats: 20
  cluster_padding_factor: 1.0
  padding_factor: 1.0
  random_rotation: false
masses:
  "1": !Quantity
    unit: dalton
    value: 1.8849990367889404
  "2": !Quantity
    unit: dalton
    value: 1.0
radii:
  "1": !Quantity
    unit: nanometer
    value: 105.0
  "2": !Quantity
    unit: nanometer
    value: 85.0
surface_potentials:
  "1": !Quantity
    unit: millivolt
    value: -50.0
  "2": !Quantity
    unit: millivolt
    value: 50.0